#!/bin/bash
# refresh-source-sync.sh -- regenerate packs/dev/.source-sync after a
# conformance pass.
#
# Run this after reviewing the dev pack AGENT.md.add against the source
# sections in Metal AGENT.md and confirming the pack fragment still reflects
# the intent correctly.  The new snapshot replaces the old one so
# release-preflight resets its drift baseline to NOW.
#
# Usage:
#   refresh-source-sync.sh [--source-file <path>]
#
#   --source-file <path>
#       Override the Metal AGENT.md path (default: the path already recorded
#       in the existing .source-sync, or ~/dogany/Metal/AGENT.md if the file
#       does not yet exist).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SYNC_FILE="$REPO_ROOT/packs/dev/.source-sync"

# Determine source file
SOURCE_FILE=""
if [[ $# -ge 2 && "$1" == "--source-file" ]]; then
    SOURCE_FILE="$2"
fi
if [[ -z "$SOURCE_FILE" && -f "$SYNC_FILE" ]]; then
    # Read first source_file from existing .source-sync
    SOURCE_FILE="$(grep -v '^#' "$SYNC_FILE" | awk -F'\t' '{print $2; exit}')"
fi
SOURCE_FILE="${SOURCE_FILE:-$HOME/dogany/Metal/AGENT.md}"

if [[ ! -f "$SOURCE_FILE" ]]; then
    echo "[refresh-source-sync] ERROR: source file not found: $SOURCE_FILE" >&2
    echo "  Pass --source-file <path> to override." >&2
    exit 1
fi

TODAY="$(date '+%Y-%m-%d')"

echo "[refresh-source-sync] source: $SOURCE_FILE"
echo "[refresh-source-sync] output: $SYNC_FILE"
echo "[refresh-source-sync] date:   $TODAY"

python3 - "$SOURCE_FILE" "$SYNC_FILE" "$TODAY" <<'PYEOF'
import sys, hashlib, textwrap

source_file, sync_file, today = sys.argv[1], sys.argv[2], sys.argv[3]

SECTIONS = [
    ("## Role", 2),
    ("### Tickets", 3),
    ("### Design grill (adversarial design review) -- 형님 지시 2026-07-01", 3),
    ("### Spec-first patching -- 형님 승인 2026-07-14", 3),
    ("### Local commit checkpoint -- 형님 지시 2026-07-07, 2026-07-08", 3),
]

def extract_section(content, heading, level):
    lines = content.split("\n")
    start = None
    for i, line in enumerate(lines):
        if line.rstrip() == heading:
            start = i
            break
    if start is None:
        return None
    end = len(lines)
    for i in range(start + 1, len(lines)):
        if lines[i].startswith("#"):
            hcount = len(lines[i]) - len(lines[i].lstrip("#"))
            if hcount <= level:
                end = i
                break
    section_lines = lines[start:end]
    while section_lines and section_lines[-1].strip() == "":
        section_lines.pop()
    return "\n".join(section_lines)

content = open(source_file, encoding="utf-8").read()
rows = []
for heading, level in SECTIONS:
    text = extract_section(content, heading, level)
    if text is None:
        print(f"  WARN: section not found: {heading!r}", file=sys.stderr)
        continue
    normalized = "\n".join(line.rstrip() for line in text.split("\n"))
    h = hashlib.sha256(normalized.encode("utf-8")).hexdigest()
    rows.append((h, source_file, heading))
    print(f"  hashed: {h[:16]}...  {heading}")

header = f"""\
# dev pack source conformance baseline
# Generated by: scripts/pack/refresh-source-sync.sh
# Snapshot date: {today}
# Source file: {source_file}
#
# Each entry records the sha256 of one pack-mirrored section (heading text
# to the next same-or-higher-level heading, trailing blank lines stripped,
# trailing whitespace per line stripped).
#
# release-preflight reads this file and warns ONLY when a listed section
# has changed since this snapshot. If the source file is absent (other
# machines), the check is skipped with an explicit note.
#
# Format:  <sha256hex>  <source_file>  <section_heading>
# Fields are tab-separated. Do not hand-edit; regenerate via:
#   scripts/pack/refresh-source-sync.sh
"""

with open(sync_file, "w", encoding="utf-8") as fh:
    fh.write(header + "\n")
    for h, sf, heading in rows:
        fh.write(f"{h}\t{sf}\t{heading}\n")

print(f"  wrote {len(rows)} entries -> {sync_file}")
PYEOF

echo "[refresh-source-sync] done."
