"""DGN-719 phase-0: render-layer parity pins (OSS == live vendored bridge).

The DGN-376/619/682/699 render layer was resynced from the vendored Dogany
bridge into this repo. Every expected literal below was GENERATED by running
the vendored bridge/formatting.py at resync time (2026-08-05) and is asserted
byte-identically here, so any future drift between the two render layers
breaks this suite instead of silently forking rendering again.

Feature pins: lists (3-tier glyphs), blockquote collapse, `>! ` expandable
fold, bold, word-only italic, strike, inline code, links, link_preview::
marker, interim-fold composition (DGN-682) and growing-fold render (DGN-699).
"""

from bridge.formatting import (
    FOLD_CAPTION_NORMAL,
    FOLD_CAPTION_STOPPED,
    FOLD_CAPTION_TIMEOUT,
    FOLD_TRUNCATION_LINE,
    INTERIM_FOLD_SEPARATOR,
    LINK_PREVIEW_MARKER,
    compose_interim_fold,
    markdown_to_telegram_html as md2html,
    render_fold_final,
    render_fold_live,
    strip_link_preview_marker,
)

# (input, vendored-generated expected output) -- byte-exact.
_MD2HTML_PINS = [
    # bold / italic / strike / inline code / links
    ("a **bold** b", "a <b>bold</b> b"),
    ("a __bold__ b", "a <b>bold</b> b"),
    ("a *ital* b", "a <i>ital</i> b"),
    ("a _ital_ b", "a <i>ital</i> b"),
    ("a *two words* b", "a *two words* b"),  # word-only italic rule
    ("a ~~gone~~ b", "a <s>gone</s> b"),
    ("run `x<y&z`", "run <code>x&lt;y&amp;z</code>"),
    (
        "[dec-094](http://console.example.com:8484/decision/dec-094)",
        '<a href="http://console.example.com:8484/decision/dec-094">dec-094</a>',
    ),
    ("[foo](bar)", "[foo](bar)"),  # non-http(s)/tg target stays literal
    # lists: 3-tier glyphs, 2-space visual indent per depth
    ("- top\n  - child\n    - grand", "• top\n  ◦ child\n    ‣ grand"),
    ("1. first\n2. second", "1. first\n2. second"),
    # blockquote collapse + `>! ` expandable fold sentinel
    ("> a\n> b\n> c", "<blockquote>a\nb\nc</blockquote>"),
    (">! secret\n> more", "<blockquote expandable>secret\nmore</blockquote>"),
    ("> a\n>! b", "<blockquote>a\nb</blockquote>"),  # sentinel first-line only
    # composite: all features in one message
    (
        "mixed\n\n- list *w*\n> quote **b**\n\n`code` and [l](https://x.io) done",
        "mixed\n\n• list <i>w</i>\n<blockquote>quote <b>b</b></blockquote>"
        '\n\n<code>code</code> and <a href="https://x.io">l</a> done',
    ),
]


def test_md2html_parity_pins():
    for src, expected in _MD2HTML_PINS:
        assert md2html(src) == expected, f"render drift for input: {src!r}"


def test_link_preview_marker_parity():
    assert LINK_PREVIEW_MARKER == "link_preview::"
    out, present = strip_link_preview_marker("body line\nlink_preview::\n")
    assert (out, present) == ("body line", True)
    out, present = strip_link_preview_marker("hello world")
    assert (out, present) == ("hello world", False)


def test_compose_interim_fold_parity():
    # DGN-682: quote-run composition, first line `>! `, blanks bare `>`,
    # code fences neutralized to '''.
    assert compose_interim_fold(["step one"], "final") == ">! step one"
    assert compose_interim_fold(["a\n\nb", "```py\nx\n```"], "final answer") == (
        ">! a\n>\n> b\n>\n> '''py\n> x\n> '''"
    )
    assert compose_interim_fold(["   \n  "], "final") == ""
    assert INTERIM_FOLD_SEPARATOR == "\n\n"


def test_growing_fold_render_parity():
    # DGN-699: live phase = plain text; finalize = caption inside the
    # expandable blockquote. DGN-851: caption TEXT moved to the bridge i18n
    # catalogs (locale-dependent), so structure is pinned via the constants
    # and the LOCKED ko copy is pinned against the ko catalog directly.
    assert render_fold_live(["step one", "step two"]) == "step one\n\nstep two"
    assert render_fold_final(["step one"], FOLD_CAPTION_NORMAL) == (
        "<blockquote expandable>" + FOLD_CAPTION_NORMAL + "\nstep one</blockquote>"
    )
    assert render_fold_final(["s1", "s2"], FOLD_CAPTION_STOPPED) == (
        "<blockquote expandable>" + FOLD_CAPTION_STOPPED
        + "\ns1\n\ns2</blockquote>"
    )
    # LOCKED ko copy pins (owner A-case 2026-08-02).
    from bridge.i18n import ko
    assert ko.STRINGS["fold_caption_normal"] == "진행 기록"
    assert ko.STRINGS["fold_caption_stopped"] == "중단됨 · 진행 기록"
    assert ko.STRINGS["fold_caption_timeout"] == "시간 초과 · 진행 기록"
    assert ko.STRINGS["fold_truncation_line"] == "…(생략)"
    assert ko.STRINGS["fold_omission_line"] == "⋯ 중략 ⋯"
